---
title: "Article search"
author: "Shifa Maqsood"

---
-Brain Activity and Functional Coupling Changes Associated with Self-Reference Effect during Both Encoding and Retrieval
-Self-Reference Effect Induced by Self-Cues Presented During Retrieval
Creator
-Can self-referentisl information improve directed forgetting? evidence from multinomial processing tree model
-The effects of self-reference versus other reference on the recall of traits and nouns
R. Maki, K. Mccaul
Published 1 March 1985
Psychology
Bulletin of the psychonomic society\
Self-reference and the encoding of personal information in depression
Remembering information related to one's self
Semantic and self-referent encoding techniques and recall of meanings of unfamiliar adjectives
Self-referential processing is distinct from semantic elaboration: Evidence from long-term memory effects in a patient with amnesia and semantic impairments
Levels of processing: A framework for memory research1
An online paradigm for exploring the self-reference effect
Sarah V. Bentley , Katharine H. Greenaway, S. Alexander Haslam
Self-referential encoding of source information in recollection memory
Self, Memory, and the Self-Reference Effect: An Examination of Conceptual and Methodological Issues
Semantic and self-referential processing of positive and negative trait adjectives in older adults
Elizabeth L. Glisky PhD  & Maria J. Marquine
The trouble with levels: A reexamination of Craik and Lockhart's framework for memory research.
Export  EXPORT  Add To My List Email Print © Request Permissions Share
The self-reference effect in memory: A meta-analysis.
Source memory that encoding was self-referential: the influence of stimulus characteristics
Levels of processing: the evolution of a framework
Memory for Details with Self-Referencing- further explores objects and source pf info to support self-reference 
Elaboration, organization, and the self-reference effect in memory.- opposite side